apiVersion: v1
kind: Service
metadata:
  name: telegram-news-bot
  labels:
    app: telegram-news
    component: bot
spec:
  type: ClusterIP
  selector:
    app: telegram-news
    component: bot
  ports:
    - name: http
      port: 80
      targetPort: http
